//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuarksoftDBEmailsEntities : DbContext
    {
        public QuarksoftDBEmailsEntities()
            : base("name=QuarksoftDBEmailsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Domains> Domains { get; set; }
        public virtual DbSet<EmailHeader> EmailHeader { get; set; }
        public virtual DbSet<Emails> Emails { get; set; }
        public virtual DbSet<EmailDomains> EmailDomains { get; set; }
        public virtual DbSet<EmailRecipients> EmailRecipients { get; set; }
    }
}
